version: '3.8'

services:
  mysql:
    container_name: database-mysql
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USERNAME: caiorosa
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tickets-manager
    volumes:
      - ./data/mysql:/data/mysql