import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import Sidebar from '@/app/ui/sidebar/sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Ticket Manager',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-zinc-900 text-purple-100 antialiased`}
      >
        {/* create side bar menu and content area with flex 1 */}
        <div className="flex h-screen">
          {/* Sidebar */}
          <Sidebar />
          {/* Content */}
          <div className="flex-1 p-4">{children}</div>
        </div>
      </body>
    </html>
  )
}
