import type { Metadata } from 'next'
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import { Inter } from 'next/font/google'
import './globals.css'
import Provider from '@/utils/providers'

import Sidebar from '@/app/ui/sidebar/sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Ticket Manager',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-zinc-900 text-purple-100 antialiased`}
      >
        <Provider>
          {/* create side bar menu and content area with flex 1 */}
          <div className="flex h-screen">
            {/* Sidebar */}
            <Sidebar />
            {/* Content */}
            <div className="flex-1 p-4">
              <NuqsAdapter>{children}</NuqsAdapter>
            </div>
          </div>
        </Provider>
      </body>
    </html>
  )
}
